language: node_js
node_js:
- '12'
install:
- npm install
script:
- npm run build:docs
deploy:
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: RainCache
  on:
    branch: dev
env:
  global:
    secure: PLjIYLBvDlPo/JZiZoWMqO9h+9j41SNWpzrg2Z+ZqtD9hqUr2ZNyRKhCFoe70kuBRd1EX259bOigrprMrgIc5TSTeMzNDkpI6c7kIJEFia8wWK6z/tcSsp+JSMvQ4WFb3nNWI5QZJ4YIKaKcdAC6NfCuk+j+cuQ/jZXHu/UOBpPkx4GfmSdxHrrQz/3DxBEAvNtYft82b61COUWfJX30o3dttCy/ZbLLGEj1g2GD/Dwt4WNv14ix4GrvKkyjcHcdoT1I+RiGg7QwKVdwEcrHVWO+YN1dFd+vjBbnDSPzwqIjBYmWl+yxB4BHXVG/aaVf5i6HzsX5s/9+ixYMKf4q06tHVUFuCdBamSTPYBXpqsG7GyDIiahAQPQBy04CfPKj1eMKxWvwweZ4jkuI02RPRgY4lBayoYofCIhLmjQNob6TH3f8T7gRp7CfLsMOJeIwqg2Cxi41ZANMIgQy1j8olh3PGjhzdiwYr6usKmTjUXThLHws0+zaxKkxSRFL0sEEP/431P0F0cvotqKHXutyyzpGiOzeKkvR3luUWG606Oq4DbOyB2jpmY/Dwyu+HJHRciHJJy425LxatU5jENTsJ2nU1xSgEs5l5kYZMRuTGDNw4yLu96hG2vv+5r97J+uaqS3x9fFP/bD4CoNhvNUNfbZLpWged8b1iP2Klw88CHQ=
